apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-target
spec:
  type: image
  params:
    - name: url
      value: docker.io/fpathankcs/node-api-tekton # Replace with your docker hub repo url
